// @ts-expect-error: generated by `opennextjs-cloudflare build`
import { default as handler } from './.open-next/worker.js'

type Env = { MEDIA: R2Bucket }

// Videos are served from R2 so browsers get byte-range (206) responses,
// which iOS Safari requires to play <video>.
async function serveMedia(request: Request, env: Env, key: string) {
  const object = await env.MEDIA.get(key, { range: request.headers, onlyIf: request.headers })
  if (!object) return new Response('Not found', { status: 404 })

  const headers = new Headers()
  object.writeHttpMetadata(headers)
  headers.set('etag', object.httpEtag)
  headers.set('accept-ranges', 'bytes')

  if (!('body' in object)) return new Response(null, { status: 304, headers })

  const range = object.range as { offset?: number; length?: number; suffix?: number } | undefined
  if (request.headers.has('range') && range) {
    const offset = range.suffix !== undefined ? object.size - range.suffix : (range.offset ?? 0)
    const length = range.suffix ?? range.length ?? object.size - offset
    headers.set('content-range', `bytes ${offset}-${offset + length - 1}/${object.size}`)
    headers.set('content-length', String(length))
    return new Response(object.body, { status: 206, headers })
  }

  headers.set('content-length', String(object.size))
  return new Response(object.body, { headers })
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext) {
    const { pathname } = new URL(request.url)
    if (pathname.startsWith('/videos/') && (request.method === 'GET' || request.method === 'HEAD')) {
      return serveMedia(request, env, pathname.slice(1))
    }
    return handler.fetch(request, env, ctx)
  },
} satisfies ExportedHandler<Env>
